### ISSUE TITLE
as.polygons potentially undesireable behavior with categorical raster, Dissolve

### ISSUE THREAD

**Issue by souma4** [rspatial/terra#1162]
Hello, I posted this on stack exchange but realized this is likely more applicable to the report here. I'll just link to the stack exchange [Link to stack exchange]<https://stackoverflow.com/questions/76283787/r-terra-as-polygons-potentially-undesireable-behavior-with-categorical-raster> 
In summary, when using as.polygons(dissolve=T) It does not appear to be appropriately dissolving around the polygons. The workaround is to use st_union in the SF package. I am not sure if there is a terra work around. The "How-to" may be better to answer on the stack exchange, but the potential bug works better here. Let me know if you need anything.

**Comment by rhijmans** [comment]
This has likely been fixed in the development version.

**Comment by souma4** [comment]
Behavior still persists on terra 1.7-33, same code and outputs.

**Comment by souma4** [comment]
Problem still persists on 1.7-33, same  code and outputs. And my bad for accidentally hitting the wrong buttons (in case you got notifications).

**Comment by rhijmans** [comment]
Sorry about that --- I did fix a bug in it a week or so ago, so I was hopeful that it would have caught this too. Can you please provide a link to the file you are using so that I can see what it is going on?

**Comment by souma4** [comment]
Here is the data download [](https://www.landfire.gov/version_download.php#). It is the first LF 2020 download (you may need to select LF 2020 due to the default being LF 2022), Biophysical settings, BPS, CONUS. LANDFIRE doesn't have the nicest data download portal for linking to one specific file, unfortunately. I'm linking to a zip of the tif folder (it contains all the tif additional files) just in case that's more expedient [](https://drive.google.com/file/d/1OJ_X9HwME7dwFBoAztkZ7OjvM5Umw45s/view?usp=sharing)

**Comment by rhijmans** [comment]
Thanks very much for the file. What is going on is that you have a categorical `SpatRaster` where many category IDs point to the same label for the active category.  `as.polygons` does not consider that.  So you currently need to use `aggregate` after `as.polygons`. Illustration

```
setwd("../Downloads/Tif")

library(terra)
bps <- rast("LC20_BPS_220.tif")
window(bps) <- ext( -1661967, -1630391, 2563990, 2598949 )
bps1km <- aggregate(bps, 33,fun = "modal") 

plot(bps1km)
lines(as.polygons(bps1km))

activeCat(bps1km) <- 2 
p <- as.polygons(bps1km)
pa <- aggregate(p, "ZONE")

plot(bps1km, col=rainbow(25)) 
lines(pa)
```

I do not like this because it would be better to keep the memory needed for the returned polygons as small as possible. I think there needs to be a method that collapses duplicate (for the active category) IDs to simplify the raster.

**Comment by souma4** [comment]
that makes sense. I agree that keeping the memory requirements as low as possible would be nice. I know I downscaled my data because of memory limits. That may not fully go away because processing the Rast2Vec  is going to naturally use more memory, but atleast reducing the final output could be beneficial, especially if used in a broader pipeline. Regardless, it works, is functional, and can be worked around reasonably enough. Thanks for checking it out!
