### ISSUE TITLE
Reprojecting relatively large files

### ISSUE THREAD

**Issue by caiosantosnt** [rspatial/terra#1669]
When trying to reproject a large SpatRaster, I encounter the error message shown below.

```
Error: [project] cannot create dataset from source
In addition: Warning message:
../../../gdal-3.9.3/frmts/mem/memdataset.cpp, 1277: cannot allocate 1x403621047200 bytes (GDAL error 2)
```

I have tried running the process on multiple computers (Windows OS), including one with 96GB of RAM, but the same error persists. The computer I am currently using has 16GB of RAM and 218GB of free disk space. I also tried splitting the SpatRaster into multiple tiles (it took more than 12 hours), reprojecting each tile, and then merging them. However, this approach slightly changes the resolution of each tile, preventing merging and resulting in pixels with missing data at the junction between tiles (visualised in GIS). 

I don't know how to fix the issue or or work around it.  Any help is much appreciated. Thanks.

```
packageVersion("terra")
#[1] ‘1.7.83’
terra::gdal(lib="all")
#    gdal     proj     geos 
# "3.9.3"  "9.4.1" "3.12.2" 
```

CODE TO REPRODUCE THE ERROR

```
library(terra)
## Download file (~2Gb) ####
dir.create("input", FALSE, FALSE)
f <- "input/NSW_NativeVegetationExtent_v1p4_5m.tif"
if (!file.exists(f)) {
  fzip <- file.path("input", basename(url))
  options(timeout=600)
  url <- "https://datasets.seed.nsw.gov.au/dataset/72d14092-9088-48a4-896b-3a95a7e566d1/resource/9b1a3556-101a-4a48-9f5c-f0717c72ea97/download/nsw_nativevegetation_v1p4.zip"
  download.file(url, fzip, mode = "wb")
  unzip(fzip,  exdir= "input", junkpaths = TRUE)
}
## Load file
nve <- rast(f)

## project  fails
nve.3577 <- project(nve, "EPSG:3577") 
#Error: [project] cannot create dataset from source
#In addition: Warning message:
#../../../gdal-3.8.4/frmts/mem/memdataset.cpp, 1287: cannot allocate 1x403621047200 bytes (GDAL error 2) 
```

CODE TO PROCESS TILES

```
library(terra)
library(dplyr)

nve <- vrt("input/native-vegetation-extent/nve_reclassified.tif") 
partition <- FALSE

nve.proj <- tryCatch(
  project(nve, "EPSG:3577", threads = TRUE),
  error = function(e) { partition <<- TRUE}
)
  if(partition){
    chunks <- getTileExtents(nve, y = 50000) 
    chunks <- apply(chunks, MARGIN = 1, ext)
    chunks.proj <- lapply(chunks, function(tile){
      t <- terra::crop(nve, tile)
      t.projected <- terra::project(t, "EPSG:3577", method = "near")
      return(t.projected)
    })

nve.collection <- sprc(chunks.proj)

nve.merged <- merge(nve.collection, na.rm = FALSE, 
                    filename = "input/native-vegetation-extent/nve_reclassified_epsg3577.tif")
}
# Error: [merge] resolution does not match
```

**Comment by rhijmans** [comment]
Thanks. Fixed now. I simplified the first part of your code to make it easier to see what was not working. To use tiles you would need to project an empty input raster, and then make tiles from that and use these as templates.

**Comment by caiosantosnt** [comment]
Thanks for your prompt response. Robert. However, I'm still getting the same error.

I updated terra from source using
remotes::install_github("rspatial/terra")

Then I ran
r <- rast("NSW_NativeVegetationExtent_v1p4_5m.tif")
r.proj <- project(r, "EPSG:8058",
                           filename = "input/covariates/processed-covariates/nve.tif"),
                           by_util = T)
# Error: [project] cannot create dataset from source
In addition: Warning message:
../../../gdal-3.9.3/frmts/mem/memdataset.cpp, 1277: cannot allocate 1x403621047200 bytes (GDAL error 2)

**Comment by rhijmans** [comment]
Thanks, now also fixed for the `by_util=TRUE` case. (still taking a long time)
