### ISSUE TITLE
Interpolate fails when there are more than 500 columns

### ISSUE THREAD

**Issue by sgilber1** [rspatial/terra#304]
Here is a toy example:

```
library(terra)
library(magrittr)
# Random data more than 500 columns wide
nc <- 550
m <- rnorm(nc * 10) %>% matrix(nrow=10) %>% rast()
names(m) <- "m"

# Random data to build a test model
test <- rnorm(100) %>% matrix(ncol=2) %>% as.data.frame()
names(test) <- c("r", "m")
test$x <- sample(nc, nrow(test), replace = TRUE)
test$y <- sample(10, nrow(test), replace = TRUE)
out <- lm(r ~ m + x + y, test)

# predict the model on the raster data
interpolate(m, out)
```

It gives the following error:

`Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 500, 550`

**Comment by sgilber1** [comment]
Sorry about the bad formatting on the example code. I haven't figured out the formatting yet.

**Comment by rhijmans** [comment]
Thank you very much for reporting this. Fixed now.

**Comment by ateucher** [comment]
Hello - I am finding that this is still occurring with larger raster dimensions. As you can see in the two examples below, it happens in either the [initial run](https://github.com/rspatial/terra/blob/bcb2b178f71743bdb86dc79ded9c996185c02250/R/interpolate.R#L20-L27) or in the [full run](https://github.com/rspatial/terra/blob/bcb2b178f71743bdb86dc79ded9c996185c02250/R/interpolate.R#L36-L41).

``` r
library(terra)
#> terra version 1.4.8
library(magrittr)

nc <- 5000
nr <- 7000
m <- rnorm(nc * nr) %>% matrix(nrow=nr) %>% rast()
names(m) <- "m"

# Random data to build a test model
test <- rnorm(100) %>% matrix(ncol=2) %>% as.data.frame()
names(test) <- c("r", "m")
test$x <- sample(nc, nrow(test), replace = TRUE)
test$y <- sample(nr, nrow(test), replace = TRUE)
out <- lm(r ~ m + x + y, test)

# predict the model on the raster data
interpolate(m, out)
#> Error in data.frame(..., check.names = FALSE): arguments imply differing number of rows: 501, 500

# Slightly different dimensions
nc <- 5000
nr <- 6000
m <- rnorm(nc * nr) %>% matrix(nrow=nr) %>% rast()
names(m) <- "m"

# Random data to build a test model
test <- rnorm(100) %>% matrix(ncol=2) %>% as.data.frame()
names(test) <- c("r", "m")
test$x <- sample(nc, nrow(test), replace = TRUE)
test$y <- sample(nr, nrow(test), replace = TRUE)
out <- lm(r ~ m + x + y, test)

# predict the model on the raster data
interpolate(m, out)
#> Error in data.frame(..., check.names = FALSE): arguments imply differing number of rows: 30000001, 30000000
```

<sup>Created on 2021-10-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rhijmans** [comment]
Thank you. Your examples worked for me on windows with R/4.1.1, but not on linux(ubuntu) with R/4.0.2 or on Mac with R/4.0.5.

With the last commit they work on all these three configurations.

The underlying reason appears to be a loss of precision when doing math with large integers (cell numbers) and converting them to doubles prior to multiplication fixed that.

**Comment by ateucher** [comment]
That makes sense, but I would not have thought of that.  Thank you!
