### ISSUE TITLE
Error in installing terra

### ISSUE THREAD

**Issue by Hamedhm** [rspatial/terra#487]
I am trying to install terra on CentOS and get the following error

```
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -larmadillo
/usr/bin/ld: cannot find -lpoppler
/usr/bin/ld: cannot find -ljson-c
/usr/bin/ld: cannot find -lfreexl
/usr/bin/ld: cannot find -lgeos_c
/usr/bin/ld: cannot find -lkmlbase
/usr/bin/ld: cannot find -lkmldom
/usr/bin/ld: cannot find -lkmlengine
/usr/bin/ld: cannot find -lkmlxsd
/usr/bin/ld: cannot find -lkmlregionator
/usr/bin/ld: cannot find -lopenjp2
/usr/bin/ld: cannot find -lmfhdf
/usr/bin/ld: cannot find -ldf
/usr/bin/ld: cannot find -logdi
/usr/bin/ld: cannot find -lgif
/usr/bin/ld: cannot find -lgeotiff
/usr/bin/ld: cannot find -lgta
/usr/bin/ld: cannot find -lcfitsio
/usr/bin/ld: cannot find -lpq
/usr/bin/ld: cannot find -ldapclient
/usr/bin/ld: cannot find -ldapserver
/usr/bin/ld: cannot find -ldap
/usr/bin/ld: cannot find -lspatialite
/usr/bin/ld: cannot find -lsqlite3
collect2: error: ld returned 1 exit status
configure: Install failure: compilation and/or linkage problems.
configure: error: GDALAllRegister not found in libgdal.
ERROR: configuration failed for package ‘terra’
* removing ‘xxxxxxxxx/R/packages/4_0_3/terra’

```
It seems that the error is associated with the GDALAllRegister. However, the library is installed:

![image](https://user-images.githubusercontent.com/7384088/149556568-7cba993c-7d8e-4df5-a240-cb593202cd05.png)

Please can you advice?

**Comment by rhijmans** [comment]
Can you please include the full output of the install script? 
This may happen if there are multiple installations of GDAL on your system (see [here](https://stackoverflow.com/questions/46894384/cannot-install-rgdal-centos) and some other diagnostics used there.

**Comment by Hamedhm** [comment]
Hi @rhijmans 

Please see below for the output:
```

R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> install.packages('terra')
Installing package into ‘/nfs/production/parkinso/spot/mousephenotype/hamed/R/packages/4_0_3’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/terra_1.5-12.tar.gz'
Content type 'application/x-gzip' length 624884 bytes (610 KB)
==================================================
downloaded 610 KB

* installing *source* package ‘terra’ ...
** package ‘terra’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: /hps/software/spack/opt/spack/linux-centos8-sandybridge/gcc-9.3.0/gcc-9.3.0-lnsweiq6ddiz4zh3jwrepvcwhtp6oj2q/bin/gcc
configure: CXX: /hps/software/spack/opt/spack/linux-centos8-sandybridge/gcc-9.3.0/gcc-9.3.0-lnsweiq6ddiz4zh3jwrepvcwhtp6oj2q/bin/g++ -std=gnu++11
checking for gdal-config... /usr/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 3.0.4
checking GDAL version >= 2.0.1... yes
checking for gcc... /hps/software/spack/opt/spack/linux-centos8-sandybridge/gcc-9.3.0/gcc-9.3.0-lnsweiq6ddiz4zh3jwrepvcwhtp6oj2q/bin/gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /hps/software/spack/opt/spack/linux-centos8-sandybridge/gcc-9.3.0/gcc-9.3.0-lnsweiq6ddiz4zh3jwrepvcwhtp6oj2q/bin/gcc accepts -g... yes
checking for /hps/software/spack/opt/spack/linux-centos8-sandybridge/gcc-9.3.0/gcc-9.3.0-lnsweiq6ddiz4zh3jwrepvcwhtp6oj2q/bin/gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... /hps/software/spack/opt/spack/linux-centos8-sandybridge/gcc-9.3.0/gcc-9.3.0-lnsweiq6ddiz4zh3jwrepvcwhtp6oj2q/bin/gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... no
checking GDAL: linking with --libs and --dep-libs... no
/usr/lib64/libgdal.so: undefined reference to `PQcmdStatus@RHPG_9.6'
/usr/lib64/libgdal.so: undefined reference to `PQfname@RHPG_9.6'
/usr/lib64/libgdal.so: undefined reference to `PQsetNoticeProcessor@RHPG_9.6'
/usr/lib64/libgdal.so: undefined reference to `PQftable@RHPG_9.6'
/usr/lib64/libgdal.so: undefined reference to `PQstatus@RHPG_9.6'
/usr/lib64/libgdal.so: undefined reference to `PQftablecol@RHPG_9.6'
/usr/lib64/libgdal.so: undefined reference to `PQconnectdb@RHPG_9.6'
/usr/lib64/libgdal.so: undefined reference to `PQescapeStringConn@RHPG_9.6'
/usr/lib64/libgdal.so: undefined reference to `lo_close@RHPG_9.6'
/usr/lib64/libgdal.so: undefined reference to `PQputCopyEnd@RHPG_9.6'
/usr/lib64/libgdal.so: undefined reference to `PQgetvalue@RHPG_9.6'
/usr/lib64/libgdal.so: undefined reference to `PQgetisnull@RHPG_9.6'
/usr/lib64/libgdal.so: undefined reference to `PQftype@RHPG_9.6'
/usr/lib64/libgdal.so: undefined reference to `PQfmod@RHPG_9.6'
/usr/lib64/libgdal.so: undefined reference to `lo_creat@RHPG_9.6'
/usr/lib64/libgdal.so: undefined reference to `PQresultStatus@RHPG_9.6'
/usr/lib64/libgdal.so: undefined reference to `lo_read@RHPG_9.6'
/usr/lib64/libgdal.so: undefined reference to `PQexec@RHPG_9.6'
/usr/lib64/libgdal.so: undefined reference to `PQsetClientEncoding@RHPG_9.6'
/usr/lib64/libgdal.so: undefined reference to `PQgetlength@RHPG_9.6'
/usr/lib64/libgdal.so: undefined reference to `PQputCopyData@RHPG_9.6'
/usr/lib64/libgdal.so: undefined reference to `PQgetResult@RHPG_9.6'
/usr/lib64/libgdal.so: undefined reference to `lo_write@RHPG_9.6'
/usr/lib64/libgdal.so: undefined reference to `PQfinish@RHPG_9.6'
/usr/lib64/libgdal.so: undefined reference to `PQclear@RHPG_9.6'
/usr/lib64/libgdal.so: undefined reference to `PQerrorMessage@RHPG_9.6'
/usr/lib64/libgdal.so: undefined reference to `PQnfields@RHPG_9.6'
/usr/lib64/libgdal.so: undefined reference to `lo_open@RHPG_9.6'
/usr/lib64/libgdal.so: undefined reference to `PQexecParams@RHPG_9.6'
/usr/lib64/libgdal.so: undefined reference to `PQntuples@RHPG_9.6'
/usr/lib64/libgdal.so: undefined reference to `PQresultErrorMessage@RHPG_9.6'
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -larmadillo
/usr/bin/ld: cannot find -lpoppler
/usr/bin/ld: cannot find -ljson-c
/usr/bin/ld: cannot find -lfreexl
/usr/bin/ld: cannot find -lgeos_c
/usr/bin/ld: cannot find -lkmlbase
/usr/bin/ld: cannot find -lkmldom
/usr/bin/ld: cannot find -lkmlengine
/usr/bin/ld: cannot find -lkmlxsd
/usr/bin/ld: cannot find -lkmlregionator
/usr/bin/ld: cannot find -lopenjp2
/usr/bin/ld: cannot find -lmfhdf
/usr/bin/ld: cannot find -ldf
/usr/bin/ld: cannot find -logdi
/usr/bin/ld: cannot find -lgif
/usr/bin/ld: cannot find -lgeotiff
/usr/bin/ld: cannot find -lgta
/usr/bin/ld: cannot find -lcfitsio
/usr/bin/ld: cannot find -lpq
/usr/bin/ld: cannot find -ldapclient
/usr/bin/ld: cannot find -ldapserver
/usr/bin/ld: cannot find -ldap
/usr/bin/ld: cannot find -lspatialite
/usr/bin/ld: cannot find -lsqlite3
collect2: error: ld returned 1 exit status
configure: Install failure: compilation and/or linkage problems.
configure: error: GDALAllRegister not found in libgdal.
ERROR: configuration failed for package ‘terra’
* removing ‘/nfs/production/parkinso/spot/mousephenotype/hamed/R/packages/4_0_3/terra’

The downloaded source packages are in
        ‘/tmp/RtmpWPxSp6/downloaded_packages’
Warning message:
In install.packages("terra") :
  installation of package ‘terra’ had non-zero exit status
```

Thanks again.

**Comment by rhijmans** [comment]
And this?

```
gdal-config --libs
which gdal-config
gdal-config --version
```

**Comment by rhijmans** [comment]
Also, a good way to look for leads is to search for GDAL/CentOS issues when installing `sf` or `rgdal` as these packages also depend on GDAL but have been around for longer.

**Comment by Hamedhm** [comment]
```
[xxx@codon-login-02 ~]$ gdal-config --libs
-L/usr/lib64 -lgdal
[xxx@codon-login-02 ~]$ which gdal-config
/usr/bin/gdal-config
[xxx@codon-login-02 ~]$ gdal-config --version
3.0.4
```

Thanks again.

**Comment by rhijmans** [comment]
That all looks good. Have you been able to resolve this? I am no expert in these matters, but @rsbivand may have advice.

**Comment by rsbivand** [comment]
How was GDAL installed? From the error message, `PQ` suggests that the GDAL being found while running the configure script was built with PostgreSQL support, but that those libraries are not found when configure tests execute. Do you have multiple installs of GDAL? In general, installing a single GDAL from source after removing all binary installs is much less troublesome than sorting out binary installs, provided that you have the experience and admin. rights.

**Comment by Hamedhm** [comment]
Hi,

Thank you for helping me with this thread. I made some changes to the LD_LIBRARY_PATH and solved the majority of issues, however, it seems that one problem is still left. Please see the error below:

```
...
** R
** inst
** byte-compile and prepare package for lazy loading
in method for ‘sds’ with signature ‘x="stars"’: no definition for class “stars”
in method for ‘sds’ with signature ‘x="stars_proxy"’: no definition for class “stars_proxy”
in method for ‘coerce’ with signature ‘"stars","SpatRasterDataset"’: no definition for class “stars”
in method for ‘coerce’ with signature ‘"ggmap","SpatRaster"’: no definition for class “ggmap”
in method for ‘coerce’ with signature ‘"sf","SpatVector"’: no definition for class “sf”
in method for ‘coerce’ with signature ‘"sfc","SpatVector"’: no definition for class “sfc”
in method for ‘coerce’ with signature ‘"sfg","SpatVector"’: no definition for class “sfg”
in method for ‘coerce’ with signature ‘"XY","SpatVector"’: no definition for class “XY”
in method for ‘coerce’ with signature ‘"im","SpatRaster"’: no definition for class “im”
in method for ‘coerce’ with signature ‘"SpatVector","Spatial"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"Spatial","SpatVector"’: no definition for class “Spatial”
Creating a generic function for ‘ncol’ from package ‘base’ in package ‘terra’
in method for ‘ext’ with signature ‘x="sf"’: no definition for class “sf”
in method for ‘ext’ with signature ‘x="Extent"’: no definition for class “Extent”
in method for ‘ext’ with signature ‘x="Raster"’: no definition for class “Raster”
in method for ‘ext’ with signature ‘x="Spatial"’: no definition for class “Spatial”
in method for ‘wrap’ with signature ‘x="Spatial"’: no definition for class “Spatial”
in method for ‘rast’ with signature ‘x="stars"’: no definition for class “stars”
in method for ‘rast’ with signature ‘x="stars_proxy"’: no definition for class “stars_proxy”
in method for ‘show’ with signature ‘"Rcpp_SpatDataFrame"’: no definition for class “Rcpp_SpatDataFrame”
in method for ‘show’ with signature ‘"Rcpp_SpatCategories"’: no definition for class “Rcpp_SpatCategories”
in method for ‘geomtype’ with signature ‘x="Spatial"’: no definition for class “Spatial”
in method for ‘vect’ with signature ‘x="Spatial"’: no definition for class “Spatial”
in method for ‘vect’ with signature ‘x="sf"’: no definition for class “sf”
in method for ‘vect’ with signature ‘x="sfc"’: no definition for class “sfc”
in method for ‘vect’ with signature ‘x="XY"’: no definition for class “XY”
** help
*** installing help indices
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘terra’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/xxxyyyzzz/R/packages/4_0_3/00LOCK-terra/00new/terra/libs/terra.so':
  /lib64/libk5crypto.so.3: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘xxxyyyzzz/R/packages/4_0_3/terra’

The downloaded source packages are in
        ‘/tmp/Rtmpvumr3F/downloaded_packages’
Warning message:
In install.packages("terra") :
  installation of package ‘terra’ had non-zero exit status
```
It seems that it complains about libk5crypto.so.3 library. I checked that and it is installed:
```
$ ldconfig -p | grep libk5crypto.so.3
        libk5crypto.so.3 (libc6,x86-64) => /lib64/libk5crypto.so.3
```

Do you have any suggestion please?

**Comment by rsbivand** [comment]
https://github.com/open-ce/openmpi-feedstock/issues/19

The problem you're seeing here is that the version of the Kerberos 5 libraries and the version of OpenSSL you're using are incompatible.
On most distros, OpenSSH is compiled with Kerberos 5 support. The libraries used for cryptography for Kerberos are linked with OpenSSL in your case.

On the freshly new installed RHEL 8.3 I installed vagrant and vagrant-libvirt and I encountered the following error during vagrant up:

https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1203

/usr/lib64/libk5crypto.so.3: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b - /home/user/.vagrant.d/gems/2.6.6/gems/ruby-libvirt-0.7.1/lib/_libvirt.so
Please see https://github.com/vagrant-libvirt/vagrant-libvirt#additional-notes-for-fedora-and-similar-linux-distributions

Unfortunately I don't know of any way of solving this because it is essentially caused by a mismatch in the compile options for libraries that are required by libvirt and on the system vs what vagrant is linked against.

https://forum.ansys.com/discussion/24790/has-anyone-seen-lib64-libk5crypto-so-3-undefined-symbol-evp-kdf-ctrl-version-openssl-1-1-1b

Found the following concerning your error...

“The problem you're seeing here is that the version of the Kerberos 5 libraries and the version of OpenSSL you're using are incompatible.”

https://unix.stackexchange.com/questions/594618/git-push-error-undefined-symbol-evp-kdf-ctrl-version-openssl-1-1-1b

says “You should reinstall the krb5-libs and openssl packages first, and see if that works. If you've installed any local copies of OpenSSL or Kerberos (look in /usr/local/lib and /usr/local/lib64), then delete them and run ldconfig.”

Does any of that look familiar?

**Comment by Hamedhm** [comment]
@rsbivand thank you very much for your help. I will pass it to our IT team.

Thanks very much.

**Comment by rhijmans** [comment]
I assume this has been solved. If not, feel free to continue the conversation.

**Comment by Hamedhm** [comment]
Sorry for the late update.

We ultimately solved the issue by moving to Conda. I did not find any solution with plain R and our IT team told me that they cannot really do much with this issue. 

I still have a feeling that the problem may sit somewhere in CentOs 8 but I am not a technical guy to say a deterministic statement.

Thanks so so much for your kind help and support.

**Comment by HCharlie** [comment]
I also have smilar issues in Ubuntu 18.04, R version 4.1.3, I followed the instructions on the [readme](https://github.com/rspatial/terra#linux), and I still get below error messages

```
/libpoppler.so: undefined reference to `NSS_CMSMessage_Destroy@NSS_3.2'
/opt/conda/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: /usr/lib/x86_64-linux-gnu/libgeos_c.so: undefined reference to `geos::geom::Geometry::isEquivalentClass(geos::geom::Geometry const*) const'
/opt/conda/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: /usr/lib/x86_64-linux-gnu/libodbc.so: undefined reference to `lt_dlclose'
/opt/conda/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: /usr/lib/libgdal.so: undefined reference to `sqlite3_result_double'
collect2: error: ld returned 1 exit status
configure: Install failure: compilation and/or linkage problems.
configure: error: GDALAllRegister not found in libgdal.
ERROR: configuration failed for package ‘terra’
* removing ‘/usr/local/lib/R/site-library/terra’

The downloaded source packages are in
        ‘/tmp/downloaded_packages’
[1] "R testing loading library(terra)"
Error in library(pkg, character.only = TRUE) :
  there is no package called ‘terra’
```

any idea how to fix it?

**Comment by HCharlie** [comment]
Hi @rsbivand , thanks for your fast reply, and before I install the package this way, do you know if there's some elegant way to detect whether there're multiple GDAL installed and if so, is there an recommended way to remove them?

**Comment by HCharlie** [comment]
I will share my steps:
1. first trial of installing terra, saying `configure: error: gdal-config not found or not executable.`

```
trying URL 'https://ftp.gwdg.de/pub/misc/cran/src/contrib/terra_1.5-21.tar.gz'
Content type 'application/octet-stream' length 636954 bytes (622 KB)
==================================================
downloaded 622 KB

* installing *source* package ‘terra’ ...
** package ‘terra’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: /opt/conda/bin/x86_64-conda-linux-gnu-cc
configure: CXX: /opt/conda/bin/x86_64-conda-linux-gnu-c++
checking for gdal-config... no
no
configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package ‘terra’
* removing ‘/usr/local/lib/R/site-library/terra’

The downloaded source packages are in
        ‘/tmp/downloaded_packages’
[1] "R testing loading library(terra)"
Error in library(pkg, character.only = TRUE) :
  there is no package called ‘terra’
In addition: Warning message:
In install.packages(argv, lib.loc, repos, quiet = FALSE, verbose = FALSE,  :
  installation of package ‘terra’ had non-zero exit status
```
2. run `sudo apt-get install libgdal-dev` successfully
3. install terra again
```
(base) nbuser@jupyter-chhan:~$ Rscript -e "install.packages('terra')" > log.txt
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://ftp.gwdg.de/pub/misc/cran/src/contrib/terra_1.5-21.tar.gz'
Content type 'application/octet-stream' length 636954 bytes (622 KB)
==================================================
downloaded 622 KB

* installing *source* package ‘terra’ ...
** package ‘terra’ successfully unpacked and MD5 sums checked
** using staged installation
configure: error: GDALAllRegister not found in libgdal.
ERROR: configuration failed for package ‘terra’
* removing ‘/usr/local/lib/R/site-library/terra’

The downloaded source packages are in
        ‘/tmp/RtmpfXZ5HJ/downloaded_packages’
Warning message:
In install.packages("terra") :
  installation of package ‘terra’ had non-zero exit status
```

content in the log.txt:
https://gist.github.com/HCharlie/d3e4ec902ca0fa33d29c7c457d7ca692

**Comment by rsbivand** [comment]
Try using `R CMD INSTALL terra_1.5-21.tar.gz`

Was R installed using conda gcc? I think not. Was R installed source or binary?

Please run `tar zxvf terra_1.5-21.tar.gz`, try to run `terra/configure` to expose the complete configure step. Try to run `gdal-config` itself.

**Comment by rsbivand** [comment]
Look in `gdal-config --libs` but look to see whether there is a `libgdal.so` anywhere else. Also run the `configure` scripts from **sf** and **rgdal** which are more verbose. I do not run your system, and cannot help more at all. Try perhaps R-sig-debian, or best local help. I install R, GDAL, GEOS, PROJ etc. from source, and am very careful to avoid any installs like conda etc. Does `echo $LD_LIBRARY_PATH` say anything - it should be empty.

**Comment by meteorolog90** [comment]
I have similar problem with the terra package on CentOS :
`
installing to /users/hips001/bin/R-hips/renv/library/R-3.6/x86_64-redhat-linux-gnu/00LOCK-terra/00new/terra/libs
** R
** inst
** byte-compile and prepare package for lazy loading
in method for 'sds' with signature 'x="stars"': no definition for class "stars"
in method for 'sds' with signature 'x="stars_proxy"': no definition for class "stars_proxy"
in method for 'svc' with signature 'x="sf"': no definition for class "sf"
in method for 'coerce' with signature '"stars","SpatRasterDataset"': no definition for class "stars"
in method for 'coerce' with signature '"ggmap","SpatRaster"': no definition for class "ggmap"
in method for 'coerce' with signature '"sf","SpatRaster"': no definition for class "sf"
in method for 'coerce' with signature '"sf","SpatVector"': no definition for class "sf"
in method for 'coerce' with signature '"sfc","SpatVector"': no definition for class "sfc"
in method for 'coerce' with signature '"sfg","SpatVector"': no definition for class "sfg"
in method for 'coerce' with signature '"XY","SpatVector"': no definition for class "XY"
in method for 'coerce' with signature '"im","SpatRaster"': no definition for class "im"
in method for 'coerce' with signature '"SpatVector","Spatial"': no definition for class "Spatial"
in method for 'coerce' with signature '"Spatial","SpatVector"': no definition for class "Spatial"
in method for 'coerce' with signature '"SpatialGrid","SpatRaster"': no definition for class "SpatialGrid"
Creating a generic function for 'ncol' from package 'base' in package 'terra'
in method for 'ext' with signature 'x="sf"': no definition for class "sf"
in method for 'ext' with signature 'x="Extent"': no definition for class "Extent"
in method for 'ext' with signature 'x="Raster"': no definition for class "Raster"
in method for 'ext' with signature 'x="Spatial"': no definition for class "Spatial"
in method for 'wrap' with signature 'x="Spatial"': no definition for class "Spatial"
in method for 'rast' with signature 'x="stars"': no definition for class "stars"
in method for 'rast' with signature 'x="stars_proxy"': no definition for class "stars_proxy"
in method for 'show' with signature '"Rcpp_SpatDataFrame"': no definition for class "Rcpp_SpatDataFrame"
in method for 'show' with signature '"Rcpp_SpatCategories"': no definition for class "Rcpp_SpatCategories"
in method for 'geomtype' with signature 'x="Spatial"': no definition for class "Spatial"
in method for 'vect' with signature 'x="Spatial"': no definition for class "Spatial"
in method for 'vect' with signature 'x="sf"': no definition for class "sf"
in method for 'vect' with signature 'x="sfc"': no definition for class "sfc"
in method for 'vect' with signature 'x="XY"': no definition for class "XY"
** help
*** installing help indices
  converting help for package 'terra'
    finding HTML links ... done
    NAflag                                  html
    RGB                                     html
    SpatExtent-class                        html
    SpatRaster-class                        html
    SpatVector-class                        html
    activeCat                               html
    add                                     html
    adjacent                                html
    aggregate                               html
    align                                   html
    all.equal                               html
    animate                                 html
    app                                     html
Rd warning: /tmp/RtmpVvoIJc/R.INSTALL8d3d51f59e31/terra/man/app.Rd:45: file link 'Math-methods' in package 'terra' does not exist and so has been treated as a topic
    approximate                             html
    arith-generic                           html
    as.character                            html
    as.data.frame                           html
    as.list                                 html
    as.raster                               html
    as.spatvector                           html
    atan2                                   html
    autocor                                 html
    barplot                                 html
    boundaries                              html
    boxplot                                 html
    buffer                                  html
    c                                       html
    cartogram                               html
    catalyze                                html
    cellSize                                html
    cells                                   html
    centroids                               html
    clamp                                   html
    classify                                html
    click                                   html
    coerce                                  html
    collapse                                html
    colors                                  html
    compare-generics                        html
    compareGeom                             html
    concats                                 html
    contour                                 html
    convhull                                html
    coords                                  html
    costDistance                            html
    cover                                   html
    crop                                    html
    crosstab                                html
    crs                                     html
    deepcopy                                html
    densify                                 html
    density                                 html
    depth                                   html
    describe                                html
    diff                                    html
    dimensions                              html
    direction                               html
    disaggregate                            html
    distance                                html
    dots                                    html
    draw                                    html
    erase                                   html
    expanse                                 html
    ext                                     html
    extend                                  html
    extract                                 html
    factors                                 html
    fill                                    html
    fillTime                                html
    flip                                    html
    focal                                   html
    focal3D                                 html
    focalCor                                html
    focalCpp                                html
    finding level-2 HTML links ... done

    focalMat                                html
    focalReg                                html
    focalValues                             html
    freq                                    html
    gaps                                    html
    gdal                                    html
    geometry                                html
    geomtype                                html
    global                                  html
    gridDistance                            html
    headtail                                html
    hist                                    html
    ifelse                                  html
    image                                   html
    impose                                  html
    init                                    html
    inplace                                 html
    inset                                   html
    interpolate                             html
    intersect                               html
    is.bool                                 html
    is.lonlat                               html
    isvalid                                 html
    lapp                                    html
Rd warning: /tmp/RtmpVvoIJc/R.INSTALL8d3d51f59e31/terra/man/lapp.Rd:43: file link 'math' in package 'terra' does not exist and so has been treated as a topic
    layerCor                                html
    linearUnits                             html
    lines                                   html
    makeTiles                               html
    makeVRT                                 html
    mask                                    html
    match                                   html
    math-generics                           html
    mem                                     html
    merge                                   html
    mergeTime                               html
    minmax                                  html
    modal                                   html
    mosaic                                  html
    na.omit                                 html
    names                                   html
    nearby                                  html
    north                                   html
    not.na                                  html
    origin                                  html
    pairs                                   html
    patches                                 html
    perim                                   html
    persp                                   html
    plot                                    html
    plotRGB                                 html
    predict                                 html
    project                                 html
    quantile                                html
    query                                   html
    rapp                                    html
    rast                                    html
    rasterize                               html
    rasterizeGeom                           html
    readwrite                               html
    rectify                                 html
    relate                                  html
    rep                                     html
    replace-vector                          html
    replace                                 html
    resample                                html
    rescale                                 html
    rotate                                  html
    sample                                  html
    sapp                                    html
    sbar                                    html
    scale                                   html
    scatter                                 html
    sds                                     html
    segregate                               html
    select                                  html
    selectHigh                              html
    selectRange                             html
    serialize                               html
    setValues                               html
    shade                                   html
    sharedPaths                             html
    shift                                   html
    simplify                                html
    sort                                    html
    sources                                 html
    spin                                    html
    split                                   html
    src                                     html
    stretch                                 html
    subset                                  html
    subst                                   html
    summarize-generics                      html
    summary                                 html
    svc                                     html
    symdif                                  html
    tapp                                    html
Rd warning: /tmp/RtmpVvoIJc/R.INSTALL8d3d51f59e31/terra/man/tapp.Rd:17: missing link 'time data'
    terra-package                           html
    terraOptions                            html
    terrain                                 html
    text                                    html
    time                                    html
    tmpFile                                 html
    topology                                html
    transpose                               html
    trim                                    html
    union                                   html
    unique                                  html
    units                                   html
    values                                  html
    vect                                    html
    vector_layers                           html
    voronoi                                 html
    vrt                                     html
    weighted.mean                           html
    where                                   html
    which                                   html
    width                                   html
    window                                  html
    wrap                                    html
    writeCDF                                html
    writeRaster                             html
    writeVector                             html
    xmin                                    html
    xyCellFrom                              html
    zonal                                   html
    zoom                                    html
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for 'terra' in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/users/hips001/bin/R-hips/renv/library/R-3.6/x86_64-redhat-linux-gnu/00LOCK-terra/00new/terra/libs/terra.so':
  /users/hips001/bin/R-hips/renv/library/R-3.6/x86_64-redhat-linux-gnu/00LOCK-terra/00new/terra/libs/terra.so: undefined symbol: GEOSMakeValid_r
Error: loading failed
Execution halted
ERROR: loading failed
* removing '/users/hips001/bin/R-hips/renv/library/R-3.6/x86_64-redhat-linux-gnu/terra'
Warning message:
In i.p(...) :
  installation of package '/tmp/Rtmp3e0HSU/file6d417df3796a/terra_1.5-49.tar.gz' had non-zero exit status

`
gdal, proj, sqlite, goes are ok"

`checking gdal-config usability... yes
configure: GDAL: 3.5.0
checking GDAL version >= 2.0.1... yes
checking for gcc... /opt/gnu/bin/gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /opt/gnu/bin/gcc accepts -g... yes
checking for /opt/gnu/bin/gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... /opt/gnu/bin/gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /users/hips001/bin/gdal/share/gdal/pcs.csv readable... yes
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... yes
configure: GDAL: 3.5.0
configure: pkg-config proj exists, will use it
configure: using proj.h.
checking PROJ: checking whether PROJ and sqlite3 are available for linking:... yes
checking for geos-config... /users/hips001/bin/geos/bin/geos-config
checking geos-config usability... yes
configure: GEOS: 3.9.3
checking GEOS version >= 3.4.0... yes
checking geos_c.h usability... yes
checking geos_c.h presence... yes
checking for geos_c.h... yes
checking geos: linking with -L/users/hips001/bin/geos/lib -lgeos_c... yes
`

**Comment by rsbivand** [comment]
You are pretty much on your own. This looks like multiple installs of GEOS.

**Comment by oucstar** [comment]
@rsbivand ,I am very sorry to bother you, but I have also encountered similar problems, but my problem is that the version of gdal I downloaded is too low, but I have tried various methods to download gdal, and none seems to work. Do you have any way to install a higher version of gdal 
* installing *source* package ‘terra’ ...
** package ‘terra’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: /public/home/zengqifan/anaconda3/envs/R4.1.3/bin/x86_64-conda-linux-gnu-cc
configure: CXX: /public/home/zengqifan/anaconda3/envs/R4.1.3/bin/x86_64-conda-linux-gnu-c++
checking for gdal-config... /public/home/zengqifan/anaconda3/envs/R4.1.3/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 1.9.2
checking GDAL version >= 2.0.1... no
configure: error: terra is not compatible with GDAL versions below 2.0.1
ERROR: configuration failed for package ‘terra’
* removing ‘/public/home/zengqifan/anaconda3/envs/R4.1.3/lib/R/library/terra’
* restoring previous ‘/public/home/zengqifan/anaconda3/envs/R4.1.3/lib/R/library/terra’

The downloaded source packages are in
	‘/tmp/Rtmpw2WRv1/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("terra") :
  installation of package ‘terra’ had non-zero exit status
Error: unexpected symbol in "Installing package"

**Comment by rhijmans** [comment]
For installing on anaconda see https://anaconda.org/conda-forge/r-terra and if that does not work, you should probably ask around about it over there.

**Comment by oucstar** [comment]
@rhijmans ,Hello, thank you for your reply yesterday, but I still haven't solved my problem. My problem now is that the configured version of gdal is still an early version, and I have been making mistakes in the future. I have installed terra with conda according to your method, but it doesn't seem to work, could you please give me some more suggestions ?Here are some of my errors:

* installing *source* package ‘sf’ ...
** package ‘sf’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: x86_64-conda-linux-gnu-cc
configure: CXX: x86_64-conda-linux-gnu-c++ -std=gnu++11
checking for gdal-config... /public/home/zengqifan/anaconda3/envs/R-4.1/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 1.9.2
checking GDAL version >= 2.0.1... no
configure: error: sf is not compatible with GDAL versions below 2.0.1
ERROR: configuration failed for package ‘sf’
* removing ‘/public/home/zengqifan/anaconda3/envs/R-4.1/lib/R/library/sf’

The downloaded source packages are in
	‘/tmp/Rtmpw3gqCg/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("sf") :
  installation of package ‘sf’ had non-zero exit status

Looking forward to your reply！

**Comment by rhijmans** [comment]
I have no idea how you were able to install such an old version of GDAL, or, more generally, how Conda works. I have never used it. That is why I think you could have more luck when asking this quesiton at a Conda forum or such.

**Comment by oucstar** [comment]
@rhijmans Ok, thank you for your prompt reply

**Comment by agelosnm** [comment]
> @rhijmans Ok, thank you for your prompt reply

did you manage to resolve the issue with conda? I face a similar one when I try to load the package...

GDAL (3.8.3), GEOS (3.12.1) & PROJ (9.3.1) are installed from source.

![image](https://github.com/rspatial/terra/assets/28690845/c4a31453-2f15-4172-a0aa-d19c93798c7b)

**Comment by prusswan** [comment]
rhiljman's solution worked for me:

`conda install -c conda-forge r-terra`
