### ISSUE TITLE
Is there a plan for "Raster" to "SpatRaster" method ?

### ISSUE THREAD

**Issue by statnmap** [rspatial/terra#8]
HI, 
Can we easily switch objects from `Raster/Stack/Brick` to `SpatRaster` ?  
Without having to write file on disk and then read it with `rast`?

**Comment by rhijmans** [comment]
I have now added that. You can either do `rast(x)` or `as(x, "SpatRaster")` where x is a Raster* object

**Comment by statnmap** [comment]
That was quick !  
There is a little problem in the conversion for data on disk. The `rast` conversion creates `n_layers * n_layers`

```
  f <- system.file("external/test.grd", package="raster")
  f
  r <- raster(f)
  r2 <- stack(r,r,r) # 3 layers
  r2_rast <- rast(r2) # 3 layers
  # Write the raster on disk
  writeRaster(r2, "r2.grd")
  r2_grd <- stack("r2.grd") # 3 layers
  nlayers(r2_grd)
  r2_grd_rast <- rast(r2_grd) # 9 layers
  nlyr(r2_grd_rast)
```

**Comment by rhijmans** [comment]
Thanks, I did not think of that case. Fixed now, I believe.

**Comment by ymutua** [comment]
I am opening this issue again since its seem its not resolved. Conversion of `RasterLayer` to `SpatRaster` is failing

```
r <- raster(system.file("external/test.grd", package="raster"))
r_rast <- rast(r) 
```

```
Error in methods::as(x, "SpatRaster") : 
  no method or default for coercing “RasterLayer” to “SpatRaster”
```
